# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-04 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lover1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loverdata',
            name='girlfrnd_name',
            field=models.CharField(max_length=30),
        ),
    ]
